// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"codo-cnmp/internal/model/dao/internal"
)

// internalRoleBindingDao is internal type for wrapping internal DAO implements.
type internalRoleBindingDao = *internal.RoleBindingDao

// roleBindingDao is the data access object for table role_binding.
// You can define custom methods on it to extend its functionality as you wish.
type roleBindingDao struct {
	internalRoleBindingDao
}

var (
	// RoleBinding is globally public accessible object for table role_binding operations.
	RoleBinding = roleBindingDao{
		internal.NewRoleBindingDao(),
	}
)

// Fill with you ideas below.
