// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"codo-cnmp/internal/model/dao/internal"
)

// internalUserFollowDao is internal type for wrapping internal DAO implements.
type internalUserFollowDao = *internal.UserFollowDao

// userFollowDao is the data access object for table user_follow.
// You can define custom methods on it to extend its functionality as you wish.
type userFollowDao struct {
	internalUserFollowDao
}

var (
	// UserFollow is globally public accessible object for table user_follow operations.
	UserFollow = userFollowDao{
		internal.NewUserFollowDao(),
	}
)

// Fill with you ideas below.
