// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.7.3
// - protoc             v5.27.2
// source: pb/event.v1.proto

package pb

import (
	context "context"
	audit "github.com/Ccheers/protoc-gen-go-kratos-http/audit"
	kcontext "github.com/Ccheers/protoc-gen-go-kratos-http/kcontext"
	route "github.com/Ccheers/protoc-gen-go-kratos-http/route"
	middleware "github.com/go-kratos/kratos/v2/middleware"
	selector "github.com/go-kratos/kratos/v2/middleware/selector"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

type _ = middleware.Middleware
type _ = selector.Builder
type _ = route.Route
type _ = audit.Audit

var _ = kcontext.SetKHTTPContextWithContext

const OperationEventListEvent = "/common.Event/ListEvent"

type EventHTTPServer interface {
	// ListEvent查看-云原生管理-Event-列表
	ListEvent(context.Context, *ListEventRequest) (*ListEventResponse, error)
}

func NewEventHTTPServerMiddleware() middleware.Middleware {
	return selector.Server(
		selector.Server().Path(OperationEventListEvent).Build(),
	).Path(
		OperationEventListEvent,
	).Build()
}

func RegisterEventHTTPServer(s *http.Server, srv EventHTTPServer) {
	r := s.Route("/")
	r.GET("/api/v1/event/list", _Event_ListEvent0_HTTP_Handler(srv))
}

func GenerateEventHTTPServerRouteInfo() []route.Route {
	routes := make([]route.Route, 0, 1)
	routes = append(routes, route.Route{
		Method:  "GET",
		Path:    "/api/v1/event/list",
		Comment: "查看-云原生管理-Event-列表",
	})
	return routes
}

func _Event_ListEvent0_HTTP_Handler(srv EventHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		stdCtx := kcontext.SetKHTTPContextWithContext(ctx, ctx)
		var in ListEventRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationEventListEvent)

		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListEvent(ctx, req.(*ListEventRequest))
		})
		out, err := h(stdCtx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListEventResponse)
		return ctx.Result(200, reply)
	}
}

type EventHTTPClient interface {
	ListEvent(ctx context.Context, req *ListEventRequest, opts ...http.CallOption) (rsp *ListEventResponse, err error)
}

type EventHTTPClientImpl struct {
	cc *http.Client
}

func NewEventHTTPClient(client *http.Client) EventHTTPClient {
	return &EventHTTPClientImpl{client}
}

func (c *EventHTTPClientImpl) ListEvent(ctx context.Context, in *ListEventRequest, opts ...http.CallOption) (*ListEventResponse, error) {
	var out ListEventResponse
	pattern := "/api/v1/event/list"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationEventListEvent))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
