// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: pb/event.v1.proto

package pb

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on ListEventRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *ListEventRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListEventRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListEventRequestMultiError, or nil if none found.
func (m *ListEventRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ListEventRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetClusterName()) < 1 {
		err := ListEventRequestValidationError{
			field:  "ClusterName",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for Namespace

	if utf8.RuneCountInString(m.GetControllerName()) < 1 {
		err := ListEventRequestValidationError{
			field:  "ControllerName",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for Keyword

	// no validation rules for Page

	// no validation rules for PageSize

	// no validation rules for ListAll

	if _, ok := ListEventRequest_ControllerType_name[int32(m.GetControllerType())]; !ok {
		err := ListEventRequestValidationError{
			field:  "ControllerType",
			reason: "value must be one of the defined enum values",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return ListEventRequestMultiError(errors)
	}

	return nil
}

// ListEventRequestMultiError is an error wrapping multiple validation errors
// returned by ListEventRequest.ValidateAll() if the designated constraints
// aren't met.
type ListEventRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListEventRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListEventRequestMultiError) AllErrors() []error { return m }

// ListEventRequestValidationError is the validation error returned by
// ListEventRequest.Validate if the designated constraints aren't met.
type ListEventRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListEventRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListEventRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListEventRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListEventRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListEventRequestValidationError) ErrorName() string { return "ListEventRequestValidationError" }

// Error satisfies the builtin error interface
func (e ListEventRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListEventRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListEventRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListEventRequestValidationError{}

// Validate checks the field values on EventItem with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *EventItem) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on EventItem with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in EventItemMultiError, or nil
// if none found.
func (m *EventItem) ValidateAll() error {
	return m.validate(true)
}

func (m *EventItem) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for InvolvedObjectKind

	// no validation rules for Type

	// no validation rules for Reason

	// no validation rules for Message

	// no validation rules for InvolvedObjectName

	// no validation rules for Count

	if m.FirstTimeStamp != nil {
		// no validation rules for FirstTimeStamp
	}

	if m.LastTimeStamp != nil {
		// no validation rules for LastTimeStamp
	}

	if len(errors) > 0 {
		return EventItemMultiError(errors)
	}

	return nil
}

// EventItemMultiError is an error wrapping multiple validation errors returned
// by EventItem.ValidateAll() if the designated constraints aren't met.
type EventItemMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m EventItemMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m EventItemMultiError) AllErrors() []error { return m }

// EventItemValidationError is the validation error returned by
// EventItem.Validate if the designated constraints aren't met.
type EventItemValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e EventItemValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e EventItemValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e EventItemValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e EventItemValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e EventItemValidationError) ErrorName() string { return "EventItemValidationError" }

// Error satisfies the builtin error interface
func (e EventItemValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sEventItem.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = EventItemValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = EventItemValidationError{}

// Validate checks the field values on ListEventResponse with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *ListEventResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListEventResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListEventResponseMultiError, or nil if none found.
func (m *ListEventResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *ListEventResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetList() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ListEventResponseValidationError{
						field:  fmt.Sprintf("List[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ListEventResponseValidationError{
						field:  fmt.Sprintf("List[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ListEventResponseValidationError{
					field:  fmt.Sprintf("List[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	// no validation rules for Total

	if len(errors) > 0 {
		return ListEventResponseMultiError(errors)
	}

	return nil
}

// ListEventResponseMultiError is an error wrapping multiple validation errors
// returned by ListEventResponse.ValidateAll() if the designated constraints
// aren't met.
type ListEventResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListEventResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListEventResponseMultiError) AllErrors() []error { return m }

// ListEventResponseValidationError is the validation error returned by
// ListEventResponse.Validate if the designated constraints aren't met.
type ListEventResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListEventResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListEventResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListEventResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListEventResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListEventResponseValidationError) ErrorName() string {
	return "ListEventResponseValidationError"
}

// Error satisfies the builtin error interface
func (e ListEventResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListEventResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListEventResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListEventResponseValidationError{}
