// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v5.27.2
// source: pb/resource.v1.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Resource_CreateOrUpdateResource_FullMethodName = "/resource.v1.Resource/CreateOrUpdateResource"
	Resource_DryRunResource_FullMethodName         = "/resource.v1.Resource/DryRunResource"
)

// ResourceClient is the client API for Resource service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ResourceClient interface {
	// 管理-云原生管理-Resource-Yaml创建更新
	CreateOrUpdateResource(ctx context.Context, in *CreateOrUpdateResourceRequest, opts ...grpc.CallOption) (*CreateOrUpdateResourceResponse, error)
	// 管理-云原生管理-Resource-DryRun
	DryRunResource(ctx context.Context, in *CreateOrUpdateResourceRequest, opts ...grpc.CallOption) (*CreateOrUpdateResourceResponse, error)
}

type resourceClient struct {
	cc grpc.ClientConnInterface
}

func NewResourceClient(cc grpc.ClientConnInterface) ResourceClient {
	return &resourceClient{cc}
}

func (c *resourceClient) CreateOrUpdateResource(ctx context.Context, in *CreateOrUpdateResourceRequest, opts ...grpc.CallOption) (*CreateOrUpdateResourceResponse, error) {
	out := new(CreateOrUpdateResourceResponse)
	err := c.cc.Invoke(ctx, Resource_CreateOrUpdateResource_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resourceClient) DryRunResource(ctx context.Context, in *CreateOrUpdateResourceRequest, opts ...grpc.CallOption) (*CreateOrUpdateResourceResponse, error) {
	out := new(CreateOrUpdateResourceResponse)
	err := c.cc.Invoke(ctx, Resource_DryRunResource_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ResourceServer is the server API for Resource service.
// All implementations must embed UnimplementedResourceServer
// for forward compatibility
type ResourceServer interface {
	// 管理-云原生管理-Resource-Yaml创建更新
	CreateOrUpdateResource(context.Context, *CreateOrUpdateResourceRequest) (*CreateOrUpdateResourceResponse, error)
	// 管理-云原生管理-Resource-DryRun
	DryRunResource(context.Context, *CreateOrUpdateResourceRequest) (*CreateOrUpdateResourceResponse, error)
	mustEmbedUnimplementedResourceServer()
}

// UnimplementedResourceServer must be embedded to have forward compatible implementations.
type UnimplementedResourceServer struct {
}

func (UnimplementedResourceServer) CreateOrUpdateResource(context.Context, *CreateOrUpdateResourceRequest) (*CreateOrUpdateResourceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateOrUpdateResource not implemented")
}
func (UnimplementedResourceServer) DryRunResource(context.Context, *CreateOrUpdateResourceRequest) (*CreateOrUpdateResourceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DryRunResource not implemented")
}
func (UnimplementedResourceServer) mustEmbedUnimplementedResourceServer() {}

// UnsafeResourceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ResourceServer will
// result in compilation errors.
type UnsafeResourceServer interface {
	mustEmbedUnimplementedResourceServer()
}

func RegisterResourceServer(s grpc.ServiceRegistrar, srv ResourceServer) {
	s.RegisterService(&Resource_ServiceDesc, srv)
}

func _Resource_CreateOrUpdateResource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateOrUpdateResourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourceServer).CreateOrUpdateResource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Resource_CreateOrUpdateResource_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourceServer).CreateOrUpdateResource(ctx, req.(*CreateOrUpdateResourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Resource_DryRunResource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateOrUpdateResourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourceServer).DryRunResource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Resource_DryRunResource_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourceServer).DryRunResource(ctx, req.(*CreateOrUpdateResourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Resource_ServiceDesc is the grpc.ServiceDesc for Resource service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Resource_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "resource.v1.Resource",
	HandlerType: (*ResourceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateOrUpdateResource",
			Handler:    _Resource_CreateOrUpdateResource_Handler,
		},
		{
			MethodName: "DryRunResource",
			Handler:    _Resource_DryRunResource_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb/resource.v1.proto",
}
